### ISSUE TITLE
LaTeX Example.

### ISSUE THREAD

**Issue by AdrianKoshka** [tawesoft/bach#1]
I was wondering if you could do an example `.bach` file in a LaTeX style. When you get time of course, and if you want to. I think I get the general concept of the language though.

**Comment by golightlyb** [comment]
Hello, sorry for the late reply. I agree this would be useful and hope to do this sometime this week. Many thanks for the interest!

**Comment by AdrianKoshka** [comment]
Awesome, no problem.

**Comment by golightlyb** [comment]
I've now added an example that does this

From the repo root directory:

    cat examples/article.bach | python3 python/bach2latex-simple.py > out.latex
    pdflatex out.latex

It's not fully featured but a good starting point.

Next I want to add a more complete conversion tool, a schema for LaTeX-style bach documents, and a schema validator so that LaTeX-style bach documents can be checked for conformance / errors can be picked up line by line without complicating any conversion tools.

**Comment by AdrianKoshka** [comment]
Perhaps this is my ignorance but, in `examples/article.bach` the lines:

```
article
    title="My Example Article"
    author="Grace Hopper"
    author="Alan Turing"
    date="\\today"
```

are not enclosed within parenthesis, though the rest of the example seems to adhere to the use of parenthesis.

**Comment by golightlyb** [comment]
At the very top level, the brackets are implied.

This is to avoid situations with two top-level documents, e.g:

    (document1)
    (document2)

This is similar to how an XML document cannot contain multiple root level elements.

Rather than adding this as a special error case, it's enforced by the syntax of the language. Similarly the syntax does not allow an empty document.

But I am open to changing the syntax on this, or allowing top level brackets to be optional. Do you feel that would be better?

**Comment by AdrianKoshka** [comment]
Now that you explained it, it makes much more sense. I think top level brackets being optional would be a good middle-ground.Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [tawesoft/bach] LaTeX Example. (#1)From: Ben Sarah Golightly To: tawesoft/bach CC: Theodore Seán Tubbs ,Author At the very top level, the brackets are implied.
This is to avoid situations with two top-level documents, e.g:
(document1)
(document2)

This is similar to how an XML document cannot contain multiple root level elements.
Rather than adding this as a special error case, it's enforced by the syntax of the language. Similarly the syntax does not allow an empty document.
But I am open to changing the syntax on this, or allowing top level brackets to be optional. Do you feel that would be better?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tawesoft/bach","title":"tawesoft/bach","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tawesoft/bach"}},"updates":{"snippets":[{"icon":"PERSON","message":"@golightlyb in #1: At the very top level, the brackets are implied.\r\n\r\nThis is to avoid situations with two top-level documents, e.g:\r\n\r\n    (document1)\r\n    (document2)\r\n\r\nThis is similar to how an XML document cannot contain multiple root level elements.\r\n\r\nRather than adding this as a special error case, it's enforced by the syntax of the language. Similarly the syntax does not allow an empty document.\r\n\r\nBut I am open to changing the syntax on this, or allowing top level brackets to be optional. Do you feel that would be better?"}],"action":{"name":"View Issue","url":"https://github.com/tawesoft/bach/issues/1#issuecomment-298247387"}}}

**Comment by AdrianKoshka** [comment]
So, I noticed (at least in what is considered an "old" example now) the quote marks used [here](https://github.com/tawesoft/bach/blob/master/_old/examples/article.bach#L12) are LaTeX style, would URL and other LaTeX-isms still carry over then? It would seem silly to have something like bach, but still be attached to quite a few of another languages isms.

**Comment by golightlyb** [comment]
Good point. More correctly it could read:

    (p "Lorem ipsum dolor sit amet " (qt "consectetur adipiscing") " elit. Proin laoreet velit
    non nisl rhoncus auctor. Integer commodo scelerisque est...")

**Comment by AdrianKoshka** [comment]
: D I like that idea!

**Comment by AdrianKoshka** [comment]
Another interesting thing I saw was the seeming lack of use of `\paragraph{}` and `\par. E.g. in bach:

```
article
    title="Writing LaTeX with Bach"
    author="Adrian Lucrèce Céleste"
    date="\\today"

(section title="Introduction"

    (p "Bach is ``An XML-interoperable general-purpose semantic document markup language''.")

)
```

put through the old bach2LaTeX parser, the output is:

```
% Automatically generated by /home/adrian/git/github/tawesoft/bach/_old/python/bach2latex-simple.py
%                         at 2017-08-09 03:15:44.926304

\documentclass{article}

\title{Writing LaTeX with Bach}
\author{Adrian Lucrèce Céleste}
\date{\today}

\begin{document}
 
\maketitle


\section{Introduction}
Bach is ``An XML-interoperable general-purpose semantic document markup
language''.

\end{document}
```

so why is there `(p)` when it seemingly does nothing? not that it shouldn't be there, but it should trigger the parser to generate something, correct?

**Comment by golightlyb** [comment]
It's been a while since I wrote LaTeX but I think the paragraph markup is optional?

It would be similar if you used the same source document to generate Markdown - no paragraph tags would be emitted. But the same document could then also generate HTML, where paragraphs would be tagged.

However, it would be nice to conditionally generate a LaTeX Paragraph [like this](https://tex.stackexchange.com/a/130418) if there is a title element (I'd say attribute but you probably want a element if you're putting formatting like math mode in headings)

    (p (title (math \pi) " does " (b "not") "equal 3" )
    "Paragraph text...")

**Comment by golightlyb** [comment]
I've been inconsistent with trailing whitespace too, I'm going to work on normalising that so its always sensible.

**Comment by AdrianKoshka** [comment]
Ah, I see now.
